# Generated by Django 4.2 on 2026-05-18 06:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='content',
        ),
        migrations.AddField(
            model_name='material',
            name='file',
            field=models.FileField(default='temp.pdf', upload_to='materials/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='material',
            name='uploaded_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
