# Generated by Django 4.2 on 2026-05-18 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_remove_material_content_material_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='extracted_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
