# Generated by Django 4.2 on 2026-05-18 08:59

from django.db import migrations
import pgvector.django.vector


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0004_materialchunk'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialchunk',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True),
        ),
    ]
